# Generated by Django 5.1.2 on 2024-10-19 04:08

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('last_name', models.CharField(blank=True, max_length=16, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)])),
                ('date_registered', models.DateField(auto_now=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=16, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='car_store.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('mileage', models.PositiveSmallIntegerField(default=0)),
                ('car_body', models.CharField(blank=True, choices=[('hatchback', 'Hatchback'), ('micro_compact_car', 'Micro compact car'), ('station_wagon', 'Station wagon'), ('landau', 'Landau'), ('pickup', 'Pickup'), ('van', 'Van'), ('minivan', 'Minivan'), ('sports_car', 'Sports car'), ('sedan', 'Sedan'), ('cabriolet', 'Cabriolet'), ('off-road_car', 'Off-road car'), ('limousine', 'Limousine'), ('coupe', 'Coupe'), ('crossover', 'Crossover'), ('sedan', 'Sedan')], default='sedan', max_length=64, null=True)),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('blue', 'Blue'), ('red', 'Red'), ('pink', 'Pink'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple')], default='white', max_length=16, null=True)),
                ('engine', models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('gas', 'Gas'), ('electric_engines', 'Electric engines'), ('hybrid_installation', 'Hybrid installation')], default='petrol', max_length=64, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('robotic', 'Robotic'), ('variable', 'Variable')], default='manual', max_length=16, null=True)),
                ('drive', models.CharField(blank=True, choices=[('rear', 'Rear'), ('front', 'Front'), ('four-wheel', 'Four-wheel')], default='rear', max_length=16, null=True)),
                ('rule', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=16, null=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=16, null=True)),
                ('exchange', models.CharField(blank=True, choices=[('possible', 'Possible'), ('impossible', 'Impossible')], default='possible', max_length=16, null=True)),
                ('active', models.BooleanField(default=True)),
                ('region', models.CharField(blank=True, choices=[('bishkek', 'Bishkek'), ('chui', 'Chui'), ('yssyk-kol', 'Yssyk-kol'), ('naryn', 'Naryn'), ('osh', 'Osh'), ('talas', 'Talas'), ('jalal-abad', 'Jalal-abad'), ('batken', 'Batken')], default='bishkek', max_length=16, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_store.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_store.carmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car_store.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='car_store.car')),
            ],
        ),
    ]
